export const DUMMY_KOS = [
  {
    id: 1,
    name: "Kos Cantik Putri Malang",
    image: "/comfortable-female-dormitory-room.jpg",
    location: "Jl. Kayon, Malang",
    price: 800000,
    gender: "female",
    rating: 4.8,
    reviews: 24,
    description: "Kos nyaman untuk putri dengan fasilitas lengkap",
    facilities: [1, 2, 4, 5],
    rooms: [
      { id: 101, name: "Kamar 101", type: "Single", price: 800000, available: true },
      { id: 102, name: "Kamar 102", type: "Double", price: 1200000, available: true },
      { id: 103, name: "Kamar 103", type: "Single", price: 800000, available: false },
    ],
    comments: [
      { id: 1, author: "Rina", rating: 5, text: "Sangat nyaman dan bersih!", date: "2 hari lalu" },
      { id: 2, author: "Siti", rating: 4, text: "Bagus, tapi sedikit ramai", date: "1 minggu lalu" },
    ],
  },
  {
    id: 2,
    name: "Kos Putra Sejahtera",
    image: "/modern-male-dormitory-building.jpg",
    location: "Jl. Ijen, Malang",
    price: 600000,
    gender: "male",
    rating: 4.5,
    reviews: 18,
    description: "Kos putra terjangkau dengan lokasi strategis",
    facilities: [1, 3, 5, 6],
    rooms: [
      { id: 201, name: "Kamar 201", type: "Single", price: 600000, available: true },
      { id: 202, name: "Kamar 202", type: "Single", price: 600000, available: true },
      { id: 203, name: "Kamar 203", type: "Double", price: 1000000, available: false },
    ],
    comments: [{ id: 1, author: "Budi", rating: 4, text: "Lokasi bagus dan harga terjangkau", date: "3 hari lalu" }],
  },
  {
    id: 3,
    name: "Kos Mix Harmoni Bersama",
    image: "/shared-dormitory-facility-with-common-area.jpg",
    location: "Jl. Dieng, Malang",
    price: 700000,
    gender: "mix",
    rating: 4.2,
    reviews: 12,
    description: "Kos campur dengan fasilitas terbaru",
    facilities: [1, 2, 3, 4, 5, 6],
    rooms: [
      { id: 301, name: "Kamar 301", type: "Single", price: 700000, available: true },
      { id: 302, name: "Kamar 302", type: "Single", price: 700000, available: true },
    ],
    comments: [],
  },
]

export const DUMMY_FACILITIES = [
  { id: 1, name: "WiFi", icon: "📡" },
  { id: 2, name: "AC", icon: "❄️" },
  { id: 3, name: "Kamar Mandi Dalam", icon: "🚿" },
  { id: 4, name: "Dapur Bersama", icon: "🍳" },
  { id: 5, name: "Parkir", icon: "🚗" },
  { id: 6, name: "Ruang Tamu", icon: "🛋️" },
]

export const DUMMY_BOOKINGS = [
  {
    id: 1,
    kosId: 1,
    roomId: 101,
    userId: "user1",
    status: "pending",
    checkIn: "2025-11-15",
    duration: 3,
    total: 2400000,
    date: "2025-11-06",
  },
  {
    id: 2,
    kosId: 1,
    roomId: 102,
    userId: "user2",
    status: "accepted",
    checkIn: "2025-11-20",
    duration: 1,
    total: 1200000,
    date: "2025-11-05",
  },
  {
    id: 3,
    kosId: 2,
    roomId: 201,
    userId: "user3",
    status: "rejected",
    checkIn: "2025-11-10",
    duration: 2,
    total: 1200000,
    date: "2025-11-04",
  },
]
